@// base template
@// assumption: all classifiers are classes

@openfile generated/base/$classifier_package$.base
// generated by su4sml GCG - Generic Code Generator  

@nl@nl package $classifier_package$ ;	
@foreach classifier_list
			
	@nl@nl
	class $classifier_name$
	@if hasParent
		extends $classifier_parent$ 
	@end
	@nl {
	@foreach attribute_list
	@nl @tab	public $attribute_type$ $attribute_name$ ;
	@end
	@foreach operation_list
	@nl @tab   $operation_result_type$ $operation_name$(
		@foreach argument_list
			$argument_type$ $argument_name$
		@end
		     )	
	@nl @tab  {} 
	@end
	@nl }
@end