@// base template
@// assumption: all classifiers are classes
@openfile generated/securemova/$classifier_package$.mova
@// generated by su4sml GCG - Generic Code Generator  
load /home/doserj/projects/securemova/ocl-tool-v30/ocl-tool.maude @nl
load /home/doserj/projects/securemova/ocl-tool-v30/securemova.maude @nl 

(create-security-diagram $classifier_package$ .) @nl

@foreach role_list 
(insert-role $classifier_package$ : $role_name$ .) @nl 
    @foreach superrole_list 
    (insert-role-hierarchy $classifier_package$ | $role_name$ <-> $superrole_name$ .) @nl
    @end 
@end 

@foreach subject_list
(insert-user $classifier_package$ : $subject_name$ .) @nl
    @foreach role_list 
    (insert-user-assignment $classifier_package$ | $subject_name$ <-> $role_name$ .) @nl
    @end 
@end

@foreach permission_list 
(insert-permission $classifier_package$ : $permission_name$ .) @nl
    @foreach role_list
    (insert-permission-assignment $classifier_package$ : $permission_name$ : $role_name$ .) @nl
    @end
@end



@foreach entity_list
(insert-entity $classifier_package$ : $entity_name$ .) @nl
    @foreach attribute_list
    (insert-attribute $classifier_package$ : $entity_name$ : $attribute_name$ .) @nl
    @end                  
    @foreach assocend_list
    (insert-association-end $classifier_package$ : $entity_name$ : $assocend_name$ .) @nl
    @end
    @foreach operation_list
        @if operation_isQuery 
        (insert-query-method $classifier_package$ : $entity_name$ : $operation_name$ .) @nl
        @else 
        (insert-non-query-method $classifier_package$ : $entity_name$ : $operation_name$ .)  @nl
        @end                  
    @end              
@end

@foreach constraint_list
(insert-authorization-constraint $classifier_package$ : auth$counter_next$ : $constraint_body$.) @nl
(insert-authorization-constraint-assignment $classifier_package$ : $constraint_perm$ : auth$counter$ .) @nl
@end 

@//TODO: also support composite actions (not supported in cartridge yet...)
@foreach entity_list
    @foreach createPermission_list
    (insert-atomic-create $classifier_package$ : $permission_name$ : $entity_name$ .) @nl
    @end
    @foreach deletePermission_list
    (insert-atomic-delete $classifier_package$ : $permission_name$ : $entity_name$ .) @nl
    @end
    @foreach attribute_list
        @foreach readPermission_list
        (insert-atomic-read $classifier_package$ : $permission_name$  : $entity_name$ : $attribute_name$ .) @nl
        @end
        @foreach updatePermission_list
        (insert-atomic-update $classifier_package$ : $permission_name$  : $entity_name$ : $attribute_name$ .) @nl
        @end
    @end
    @foreach operation_list
        @foreach executePermission_list
        (insert-atomic-execute $classifier_package$ : $permission_name$ : $entity_name$ : $operation_name$ .) @nl
        @end
    @end
@end

@// FIXME: insert-entity-update et al.
@// FIXME: (insert-entity-update $classifier_package$: $permission_name$ : $entity_name$ .)

