@// base template
@// assumption: all classifiers are classes

@openfile generated/securemova/$classifier_package$.mova
// generated by su4sml GCG - Generic Code Generator  

@nl@nl 
(create-security-diagram $classifier_package$ .) @nl


@foreach role_list 
(insert-role $classifier_package$ : $role_name$ .) @nl 
@end 
@// FIXME: (insert-role-hierarchy $classifier_package$ : subrole <-> superrole .)

@foreach user_list
(insert-user $classifier_package$: $user_name$ .)
@end

@foreach permission_list 
(insert-permission $classifier_package$ : $permission_name$ .) @nl
    @foreach role_list
    (insert-permission-assignment $classifier_package$ : $permission_name$ : $role_name$ .) @nl
    @end
@end



@foreach entity_list
(insert-entity $classifier_package$ : $entity_name$ .) @nl
    @foreach attribute_list
    (insert-attribute $classifier_package$ : $entity_name$ : $attribute_name$ .) @nl
    @end                  
    @foreach assocend_list
    (insert-association-end $classifier_package$ : $entity_name$ : $assocend_name$ .) @nl
    @end
    @foreach operation_list
        @if operation_isQuery 
        (insert-query-method $classifier_package$ : $entity_name$ : $operation_name$ .) @nl
        @else 
        (insert-non-query-method $classifier_package$ : $entity_name$ : $operation_name$ .)  @nl
        @end                  
    @end              
@end

@// FIXME: insert-attribute
@// FIXME: insert-method, insert-association-end, insert-non-query-method, insert-query-method

@foreach constraint_list
(insert-authorization-constraint $classifier_package$ : auth$counter_next$ : $constraint_body$.) @nl
(insert-authorization-constraint-assignment $classifier_package$ : $constraint_perm$ : auth$counter$ .) @nl
@end 


@// FIXME: insert-entity-update et al.
@// FIXME: (insert-entity-update $classifier_package$: $permission_name$ : $entity_name$ .)

